### ISSUE TITLE
Display by classification of comment

### ISSUE THREAD

**Issue by neelsmith** [cite-architecture/widgets#2]
`simple-test.html` has two values for the `data-commentBlockLabel` attribute:  `smart-comment` and `dumb-comment`.  Ideally I'd like to turn comments off/on by class, by block or by page.  Attaching 3 imgs of mockups for "turn on dumb-comment", "turn-on smart-comment" and "turn on all"
<img width="665" alt="smart" src="https://user-images.githubusercontent.com/2204294/70197159-ea6d4c80-16d8-11ea-9694-6dfd4cad1739.png">
<img width="659" alt="dumb" src="https://user-images.githubusercontent.com/2204294/70197164-ee00d380-16d8-11ea-8575-7a61a7dd2c62.png">
<img width="665" alt="all" src="https://user-images.githubusercontent.com/2204294/70197165-f22cf100-16d8-11ea-8eec-c9fb6d04cc54.png">

**Comment by Eumaeus** [comment]
Done, for now. Display turned out to be a PITA, and your author was reduced to learning flex-box in CSS and how to re-order elements with jQuery. But it remains simple, from the implementation standpoint.
